-- MySQL Script generated by MySQL Workbench
-- 08/30/15 14:05:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema moneyky
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moneyky
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moneyky` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `moneyky` ;

-- -----------------------------------------------------
-- Table `moneyky`.`snp_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneyky`.`snp_table` ;

CREATE TABLE IF NOT EXISTS `moneyky`.`snp_table` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Symbol` VARCHAR(12) NOT NULL COMMENT '',
  `Name` VARCHAR(75) NOT NULL COMMENT '',
  `sector` VARCHAR(45) NULL COMMENT '',
  `price` INT NULL COMMENT '',
  `dividend` INT NULL COMMENT '',
  `price_earnings` INT NULL COMMENT '',
  `earnings_share` INT NULL COMMENT '',
  `book_value` INT NULL COMMENT '',
  `year_low` INT NULL COMMENT '',
  `year_high` INT NULL COMMENT '',
  `market_cap` INT NULL COMMENT '',
  `ebitda` INT NULL COMMENT '',
  `price_sales` INT NULL COMMENT '',
  `price_book` INT NULL COMMENT '',
  `sec_filings` VARCHAR(255) COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneyky`.`moneykyvsnp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneyky`.`moneykyvsnp` ;

CREATE TABLE IF NOT EXISTS `moneyky`.`moneykyvsnp` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NULL COMMENT '',
  `performance` INT NULL COMMENT '',
  `benchmark` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneyky`.`portfolio_holding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneyky`.`portfolio_holding` ;

CREATE TABLE IF NOT EXISTS `moneyky`.`portfolio_holding` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT UNSIGNED NULL COMMENT '',
  `portfolio_id` INT UNSIGNED NULL COMMENT '',
  `performance_ytd` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `company_id_idx` (`company_id` ASC)  COMMENT '',
  INDEX `portfolio_id_idx` (`portfolio_id` ASC)  COMMENT '',
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `moneyky`.`snp_table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `portfolio_id`
    FOREIGN KEY (`portfolio_id`)
    REFERENCES `moneyky`.`moneykyvsnp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
